

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: factory-backend
    env_file:
      - ./backend/.env      # 建議你建立 .env，下面會說內容
    depends_on:
      - db
      - mongo
    ports:
      - "8000:8000"
    networks:
      - factory-net

  db:
    image: postgres:16
    container_name: factory-postgres
    environment:
      POSTGRES_USER: factory
      POSTGRES_PASSWORD: factory
      POSTGRES_DB: factory_yield
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - factory-net

  mongo:
    image: mongo:7
    container_name: factory-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - factory-net

networks:
  factory-net:

volumes:
  pgdata:
  mongodata:
